57 ivesti zuvu rikiavimo sekas
AplinkosMinisterija/biip-zvejyba-api pull request #59
Opened 2024-01-10 08:11 UTC by DovMa

2024-01-10 12:47 UTC, ambrazasp requested changes

2024-01-10 12:47 UTC, ambrazasp commented on services/fishTypes.service.ts
> +        return await this.call('fishTypes.updatePriority');
pamastymui - ar nevertetu `updatePriority` turet kaip metoda o ne action?

2024-01-10 12:47 UTC, ambrazasp commented on services/fishTypes.service.ts
> +    rest: 'PATCH /priority',
ar tikrai verta daryt endpoint? lokaliai galima actiona tiesiai pasikviesti + ta darys cronjob. Tuo paciu gal verta cia naudot metoda o ne action'a?

2024-01-10 12:47 UTC, ambrazasp commented on services/fishTypes.service.ts
> +    },
ar tikrai verta leisti prieiti prie find su `auth`? Yra atskiras endpointas `public/fishTypes` kuris public yra ir ima tik tam tikrus laukus. Naudojantis situo endpoint kuris bus `/api/fishTypes` atsiranda backdoor - grazinami visi field'ai + yra galimybe `populate=createdBy`. As siulyciau palikt po iprastine autorizacija (default), nes public endpointas yra kitas su field'ais predefined

2024-01-25 21:17 UTC, ambrazasp approved these changes

2024-01-25 21:17 UTC, ambrazasp commented on services/fishTypes.service.ts
> +    }
gal geriau rankiniu budu duombazeje iskart padarykime? nereikes veliau nutryninet?

2024-01-26 12:02 UTC, DovMa commented on services/fishTypes.service.ts
> +    }
gerai, tada nutrinu dabar

2024-01-26 12:06 UTC, merged